import { Game, ParamType, Service } from "../ifs";
declare const _default: {
    uid: string;
    app_id: string;
    app_name: string;
    service_id: string;
    service_name: string;
    generateAndSubmit: (event: string, ext?: ParamType) => void;
    init: (uid: string, game: Game, serice: Service) => void;
    openServicePanel: () => void;
    enterService: () => void;
    downloadService: (plugin_version: string) => void;
    gotoServiceCenter: () => void;
    gotoAccountCenter: () => void;
    gotoDashboardUrl: (target_url?: string) => void;
    gotoSampleUrl: (target_url?: string) => void;
    gotoGuideUrl: (target_url?: string) => void;
    saveParameter: () => void;
    enableService: () => void;
    disableService: () => void;
    showSettingsMenu: () => void;
    enterBindCocosAppID: () => void;
    associateAppID: () => void;
    unassociateAppID: () => void;
    ctrateGame: () => void;
    serviceIntegrationSuccess: (uid: string, game: Game, serice: Service, time: 'Building Time' | 'Editing Time') => void;
    serviceIntegrationFailed: (uid: string, game: Game, serice: Service, time: 'Building Time' | 'Editing Time', cause: string) => void;
    openService: () => void;
    openServiceSuccess: () => void;
    openServiceFailed: (cause: string) => void;
};
export default _default;
