import { ParamType, Functions } from "../../../ifs";
export declare const template: string;
export declare const style: string;
export declare const $: any;
export declare const methods: Functions;
export declare function load(_ccService: any): Promise<void>;
export declare function unload(): Promise<void>;
export declare function ready(args?: ParamType): void;
export declare function canClose(): boolean;
export declare function close(): void;
